# When executed in order, these functions accept a matrix as an argument,
# Then store it and find its inverse, which is also stored


# makeCacheMatrix sets and retrieves a matrix and its inverse

makeCacheMatrix <- function(x = matrix()) {
  mat <- NULL
  set <- function(y){
          x <<- y
          mat <<- NULL
  }
  get <- function() x
  set_invmat <- function(inverse) mat <<- inverse
  get_invmat <- function() mat
  list(set = set, get = get,
       set_invmat = set_invmat,
       get_invmat = get_invmat)
}

# cacheSolve looks into the matrix generated by makeCacheMatrix and calculates 
# its inverse. If an inverse has already been calculated, the function retrieves 
# it. 

cacheSolve <- function(x, ...) {
        ## Return a matrix that is the inverse of 'x'
  inverse <- x$get_invmat()
  if(!is.null(inverse)) {
    message("getting cached data")
    return(inverse)
  }
  data <- x$get()
  inverse <- solve(data, ...)
  x$set_invmat(inverse)
  inverse
}

test_matrix <- makeCacheMatrix(matrix(c(1, -38, 27, -1, 41, -29, 1, -34, 24), 
                                      nrow = 3, 
                                      ncol = 3))
cacheSolve(test_matrix)